name = "webmeta"
main = "src/index.ts"
compatibility_date = "2024-07-25"
compatibility_flags = [ "nodejs_compat" ]

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "KV"
id = "your_kv_id"
